### ISSUE TITLE
Need assistance to build winedebug tab.

### ISSUE THREAD

**Issue by wildtruc** [wildtruc/winestart#1]
To make a real Wine graphical helper extension, project need a winedebug tab with full explaination tips.
Sadly, my knowledge in winedebug is very short and I'm stuck.

If you know how to insert understandable tips for each winedebug option, feel free to tell. You will be very welcome.

**Comment by austin987** [comment]
You may find https://wiki.winehq.org/Wine_Developer%27s_Guide/Debugging_Wine#Debug_channels and https://wiki.winehq.org/Wine_Developer%27s_Guide/Debugging_Wine in general useful
